# Generated by Django 5.2.17 on 2026-09-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='specialization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='technician',
            index=models.Index(fields=['is_available'], name='technicians_is_avai_9de177_idx'),
        ),
        migrations.AddIndex(
            model_name='technician',
            index=models.Index(fields=['specialization'], name='technicians_special_e22737_idx'),
        ),
        migrations.AddConstraint(
            model_name='technician',
            constraint=models.CheckConstraint(condition=models.Q(('experience_years__gte', 0)), name='technician_experience_gte_0'),
        ),
    ]
