# Generated by Django 5.2.17 on 2026-09-20 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['owner'], name='cars_car_owner_i_122e77_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['brand', 'model'], name='cars_car_brand_812f04_idx'),
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.CheckConstraint(condition=models.Q(('mileage__gte', 0)), name='car_mileage_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.CheckConstraint(condition=models.Q(('year__gte', 1900), ('year__lte', 2100)), name='car_year_valid'),
        ),
    ]
