# Generated by Django 5.2.17 on 2026-09-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('cars', '0002_alter_car_color_car_cars_car_owner_i_122e77_idx_and_more'),
        ('technicians', '0002_alter_technician_specialization_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date'], name='appointment_appoint_5be6a4_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='appointment_status_8fe9d7_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['technician', 'appointment_date'], name='appointment_technic_eb394b_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('technician', 'appointment_date', 'appointment_time'), name='unique_technician_appointment_slot'),
        ),
    ]
