# Generated by Django 5.2.17 on 2026-09-19 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('spare_parts', '0001_initial'),
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('service_date', models.DateField()),
                ('mileage', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('cancelled', 'Cancelled')], default='completed', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='cars.car')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='technicians.technician')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenancePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveIntegerField()),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_usages', to='spare_parts.sparepart')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='maintenance.maintenancerecord')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('maintenance', 'spare_part'), name='unique_maintenance_spare_part')],
            },
        ),
    ]
