# Generated by Django 5.2.17 on 2026-09-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_color_car_cars_car_owner_i_122e77_idx_and_more'),
        ('maintenance', '0001_initial'),
        ('spare_parts', '0002_sparepart_spare_parts_name_2952cb_idx_and_more'),
        ('technicians', '0002_alter_technician_specialization_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['car'], name='maintenance_car_id_88ddf9_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['service_date'], name='maintenance_service_717e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['status'], name='maintenance_status_4bd260_idx'),
        ),
        migrations.AddConstraint(
            model_name='maintenancepart',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_used__gte', 1)), name='maintenance_part_quantity_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='maintenancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('mileage__gte', 0)), name='maintenance_mileage_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='maintenancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('cost__gte', 0)), name='maintenance_cost_gte_0'),
        ),
    ]
