# Generated by Django 5.2.17 on 2026-09-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare_parts', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sparepart',
            index=models.Index(fields=['name'], name='spare_parts_name_2952cb_idx'),
        ),
        migrations.AddIndex(
            model_name='sparepart',
            index=models.Index(fields=['quantity'], name='spare_parts_quantit_e3dcf0_idx'),
        ),
        migrations.AddIndex(
            model_name='sparepart',
            index=models.Index(fields=['minimum_stock'], name='spare_parts_minimum_8379c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='sparepart',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='spare_part_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='sparepart',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='spare_part_quantity_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='sparepart',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_stock__gte', 0)), name='spare_part_minimum_stock_gte_0'),
        ),
    ]
